### ISSUE TITLE
Fix exception raised in read function

### ISSUE THREAD

**Issue by rightlag** [pennsignals/aptos#8]
**Note:** This does *not* apply to all JSON schemas.

`read` function raises an exception for [this](https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v2.0/json/petstore.json) JSON schema.

```
Python 3.5.2 (default, Sep 15 2016, 07:38:42)
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from aptos.util import read
>>> read(open('./petstore.json'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/walsh/workspace/aptos/aptos/util.py", line 26, in read
    operation, referrant=specification)
  File "/Users/walsh/workspace/aptos/aptos/models.py", line 43, in load
    response, referrant=referrant)
  File "/Users/walsh/workspace/aptos/aptos/models.py", line 64, in load
    instance['schema'] = schema.resolve(referrant)
  File "/Users/walsh/workspace/aptos/aptos/primitives.py", line 219, in resolve
    value = Object.load(value, referrant=referrant)
  File "/Users/walsh/workspace/aptos/aptos/primitives.py", line 178, in load
    return super().load(instance)
  File "/Users/walsh/workspace/aptos/aptos/primitives.py", line 45, in load
    return cls(**instance)
  File "/Users/walsh/workspace/aptos/aptos/primitives.py", line 157, in __init__
    super().__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'items'
```

**Comment by rightlag** [comment]
See d3e65cc55953d0434783970bd73bea470870e620
